[package]
name = "rm-mouse"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
evdevil = "0.4.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
ssh2 = "0.9.5"
toml = "0.8"
